name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Deploy to EC2
        env:
          kakao.client.id: ${{ secrets.KAKAO_CLIENT_ID }}
          kakao.client.secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
          kakao.redirect.url: ${{ secrets.KAKAO_REDIRECT_URL }}
        run: |
          # Use AWS CLI to copy JAR file to EC2 instance and restart service
          aws s3 cp build/libs/myapp.jar s3://my-bucket/
          ssh ec2-user@ec2-instance-ip "sudo systemctl restart myapp.service"
